import { Locale, routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { Cairo,Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/NavBar";

const cairoFont = Cairo({
  variable: "--font-cairo",
  weight: ["400", "700"],
  subsets: ["arabic"],
});

const RobotoFont = Roboto({
  variable:"--font-roboto",
  weight:["100","200","300","400","500","600","700","800","900"],
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: Locale };
}>) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  return (
    <html dir={locale==='ar'? 'rtl':'ltr'} lang={locale}>
      <body className={` ${RobotoFont.variable} antialiased max-w-[1919px] mx-auto`}>
        <NextIntlClientProvider messages={messages}>
          <main>
            <Navbar locale={locale} />
            <div className="flex flex-col w-full lg:w-[90%] p-5 lg:p-10 mx-auto">

            {children}
            </div>
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
